### ISSUE TITLE
Javascript interop

### ISSUE THREAD

**Issue by torbjornvatn** [arichiardi/cursive-shadow-cljs#1]
Hi @arichiardi, great demo setup. It helped me a lot getting shadow-cljs working in Cursive.

I'm just wondering if you have gotten Javascript inter-op references to work.

I get `cannot be Resolved` all over the place. The clojure/cljs dependencies works just fine.

![screenshot 2018-12-13 at 11 41 44](https://user-images.githubusercontent.com/4453/49933515-1c840e00-fecc-11e8-8636-2d6f9dc73b23.png)

**Comment by arichiardi** [comment]
Unfortunately Cursive does not seem to support those things properly yeah, probably worth a feature request there...thanks for the nice words!

**Comment by torbjornvatn** [comment]
Ok, thanks for the info 👍
